from dotenv import load_dotenv
from google import genai
import os
import json

from typing import Type, Optional, Any
from pydantic import BaseModel, ValidationError

load_dotenv()


class GeminiClient:
    """
    Wrapper for Google Gemini API with JSON extraction and validation.
    """

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize Gemini client.
        
        Args:
            api_key: Optional API key. If not provided, reads from GEMINI_API_KEY env var.
        """
        self.api_key = api_key or os.getenv('GEMINI_API_KEY')
        
        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY not found. Set it in .env file or pass to constructor."
            )
        
        # Initialize the client
        self.client = genai.Client(api_key=self.api_key)

    def generate(self, prompt: str, model: str = "gemini-3-flash-preview") -> str:
        """
        Generate a raw text response from a Gemini model.

        Args:
            prompt: The input prompt sent to the Gemini model.
            model: Gemini model identifier (default: gemini-3-flash-preview)

        Returns:
            str: Raw text output generated by the model.

        Raises:
            Exception: If API call fails
        """
        try:
            response = self.client.models.generate_content(
                model=model,
                contents=prompt
            )
            return response.text
        except Exception as e:
            raise Exception(f"Gemini API error: {str(e)}")

    def extract_json(
        self,
        prompt: str,
        schema: Optional[Type[BaseModel]] = None,
        model: str = "gemini-3-flash-preview",
        strict: bool = True
    ) -> Any:
        """
        Extract JSON from Gemini response and optionally validate against Pydantic schema.

        Args:
            prompt: The input prompt (should instruct model to return JSON)
            schema: Optional Pydantic model for validation
            model: Gemini model to use
            strict: If True, raise exception on validation failure.
                   If False, return raw dict even if validation fails.

        Returns:
            - If schema provided and validation succeeds: Pydantic model instance
            - If schema provided but strict=False and validation fails: raw dict
            - If no schema: raw dict

        Raises:
            ValueError: If response is not valid JSON or schema validation fails (strict=True)
        """
        # Get raw response from model
        raw_text = self.generate(prompt, model)

        # Parse JSON
        try:
            parsed_json = json.loads(raw_text)
        except json.JSONDecodeError as e:
            # Try to extract JSON from markdown code blocks
            if "```json" in raw_text:
                try:
                    json_start = raw_text.index("```json") + 7
                    json_end = raw_text.index("```", json_start)
                    json_str = raw_text[json_start:json_end].strip()
                    parsed_json = json.loads(json_str)
                except (ValueError, json.JSONDecodeError):
                    raise ValueError(
                        f"Model did not return valid JSON: {e}\n\nRaw output:\n{raw_text[:500]}..."
                    )
            else:
                raise ValueError(
                    f"Model did not return valid JSON: {e}\n\nRaw output:\n{raw_text[:500]}..."
                )

        # If no schema, return raw dict
        if schema is None:
            return parsed_json

        # Validate against schema
        try:
            validated = schema.model_validate(parsed_json)
            return validated
        except ValidationError as e:
            if strict:
                raise ValueError(
                    f"Schema validation failed:\n{e}\n\nRaw JSON:\n{json.dumps(parsed_json, indent=2)[:1000]}..."
                )
            # Non-strict mode: return raw dict
            return parsed_json

    def answer_from_context(
        self, 
        context: str, 
        question: str,
        model: str = "gemini-3-flash-preview"
    ) -> str:
        """
        Answer a question based on provided context.
        
        Args:
            context: The context information (e.g., trial JSON)
            question: The question to answer
            model: Gemini model to use
            
        Returns:
            str: The answer
        """
        prompt = f"""Answer the following question based ONLY on the provided context.
Do not use external knowledge.

Context:
{context}

Question:
{question}

Answer:"""
        
        return self.generate(prompt, model).strip()
