from dotenv import load_dotenv
from google import genai
import os
import json
import re

load_dotenv()

class GeminiClient:
    def __init__(self):
        self.client = genai.Client()

        if not os.getenv('GEMINI_API_KEY'):
            raise ValueError("GEMINI_API_KEY not found in environment variables")
        
    def generate(self, prompt: str, model: str): 
        """
        Generate a raw text response from a Gemini model.

        This method is a thin wrapper around the Gemini SDK and returns
        the model's unstructured text output exactly as generated.

        Args:
            prompt (str): The input prompt sent to the Gemini model.
            model (str): Gemini model identifier, e.g.
                - "gemini-3-flash-preview"
                - "gemini-3-pro-preview"

        Returns:
            str: Raw text output generated by the model. No formatting,
            validation, or post-processing is applied.

        Notes:
            - This method does NOT guarantee structured or JSON output.
            - Use `extract_json()` for tasks requiring schema enforcement.
        """

        response = self.client.models.generate_content(
            model=model,
            contents=prompt
        )
        return response.text
    
    def extract_json(
        self,
        prompt: str,
        model: str = "gemini-3-flash-preview",
        max_retries: int = 2,
    ) -> dict:
        """
        Enforce JSON-only output and safely parse it.
        """

        system_instruction = (
            "You are a strict JSON generator. "
            "Respond ONLY with valid JSON. "
            "No markdown, no explanations, no extra text."
        )

        full_prompt = f"{system_instruction}\n\n{prompt}"

        last_error = None

        for _ in range(max_retries + 1):
            raw = self.generate(full_prompt, model)

            try:
                return json.loads(raw)
            except json.JSONDecodeError as e:
                last_error = e

        raise ValueError(f"Gemini did not return valid JSON: {last_error}")